server {
    listen 80;
    listen [::]:80;
    server_name labs.heyrickishere.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
    }

    return 301 https://labs.heyrickishere.com$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name labs.heyrickishere.com;

    allow 127.0.0.1;
    allow ::1;
    include /etc/nginx/snippets/cloudflare-allowlist.conf;

    client_max_body_size 120M;

    ssl_certificate /etc/letsencrypt/live/labs.heyrickishere.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/labs.heyrickishere.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://127.0.0.1:4020;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;
    }
}
